hostonly_cmdline="no"
hostonly="no"
compress="xz"
omit_dracutmodules+=" multipath "
add_dracutmodules+=" livenet dmsquash-live "
add_dracutmodules+=" mdraid "
mdadmconf="yes"
install_items+=" /etc/mdadm.conf "
kernel_cmdline=" rd.auto=1 rd.md=1 "
install_items+=" /etc/udev/rules.d/99-raid-partlabel.rules "
